import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  page: { flex: 1, backgroundColor: '#F3F4F1' },
  centro: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  header: { padding: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  h1: { fontSize: 22, fontWeight: '700', color: '#1C2321' },
  sub: { fontSize: 14, color: '#5B655F', marginTop: 2 },
  h2: { fontSize: 18, fontWeight: '700', marginBottom: 16 },
  toolbar: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 24, marginBottom: 10, gap: 10 },
  busca: { flex: 1, minWidth: 120, borderWidth: 1, borderColor: '#D8DBD5', borderRadius: 7, paddingVertical: 8, paddingHorizontal: 10, backgroundColor: '#fff', fontSize: 14 },
  filtros: { paddingHorizontal: 24, marginBottom: 14, flexGrow: 0 },
  filtroBtn: { borderWidth: 1, borderColor: '#D8DBD5', backgroundColor: '#fff', borderRadius: 7, paddingVertical: 7, paddingHorizontal: 12, marginRight: 6 },
  filtroBtnAtivo: { backgroundColor: '#2F4B3F', borderColor: '#2F4B3F' },
  filtroTxt: { fontSize: 13, color: '#5B655F' },
  filtroTxtAtivo: { color: '#fff', fontWeight: '600' },
  btn: { backgroundColor: '#2F4B3F', borderRadius: 7, paddingVertical: 9, paddingHorizontal: 16, alignItems: 'center' },
  btnTxt: { color: '#fff', fontWeight: '600', fontSize: 14 },
  btnLink: { color: '#2F4B3F', fontSize: 13, fontWeight: '600' },
  btnPerigo: { color: '#A4302A', fontSize: 14 },
  btnCancelar: { color: '#5B655F', fontSize: 14, paddingVertical: 9 },
  card: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#D8DBD5', borderRadius: 10, padding: 14, marginHorizontal: 24, marginBottom: 8 },
  cardLinha: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  cardTitulo: { fontSize: 15, fontWeight: '600', color: '#1C2321' },
  cardSub: { fontSize: 12.5, color: '#5B655F', marginTop: 2 },
  badge: { borderRadius: 20, paddingVertical: 4, paddingHorizontal: 10 },
  badgeTxt: { fontSize: 12, fontWeight: '600' },
  vazio: { textAlign: 'center', color: '#5B655F', marginTop: 60 },
  overlay: { flex: 1, backgroundColor: 'rgba(20,24,22,0.45)', alignItems: 'center', justifyContent: 'center', padding: 16 },
  modal: { backgroundColor: '#fff', borderRadius: 12, width: '100%', maxWidth: 480, maxHeight: '90%' },
  campo: { marginBottom: 13 },
  label: { fontSize: 12.5, fontWeight: '600', color: '#5B655F', marginBottom: 5 },
  input: { borderWidth: 1, borderColor: '#D8DBD5', borderRadius: 7, paddingVertical: 9, paddingHorizontal: 10, fontSize: 14, backgroundColor: '#F3F4F1' },
  inputMulti: { minHeight: 60, textAlignVertical: 'top' },
  linha: { flexDirection: 'row', gap: 10 },
  linhaSwitch: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  opcaoBtn: { flex: 1, borderWidth: 1, borderColor: '#D8DBD5', borderRadius: 7, paddingVertical: 9, alignItems: 'center', marginBottom: 14 },
  opcaoBtnAtiva: { backgroundColor: '#2F4B3F', borderColor: '#2F4B3F' },
  opcaoTxt: { fontSize: 13, color: '#5B655F' },
  opcaoTxtAtiva: { color: '#fff', fontWeight: '600' },
  acoes: { flexDirection: 'row', alignItems: 'center', marginTop: 6, gap: 10 },
});
